# Generated by Django 5.2.6 on 2025-09-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Código')),
                ('nome', models.CharField(max_length=150)),
                ('unidade', models.CharField(help_text='Ex: un, cx, kg, m', max_length=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.categoria')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['sku'], name='estoque_pro_sku_a5fad6_idx'), models.Index(fields=['nome'], name='estoque_pro_nome_116d41_idx')],
            },
        ),
    ]
