# Generated by Django 5.2.6 on 2025-09-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produto',
            name='estoque_pro_sku_a5fad6_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='estoque_pro_nome_116d41_idx',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sku',
        ),
        migrations.AddField(
            model_name='produto',
            name='especificacoes',
            field=models.TextField(blank=True, help_text='Detalhes técnicos, voltagem, dimensões, etc.', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
