# Generated by Django 5.2.6 on 2025-09-24 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('estoque', '0003_produto_quantidade'),
]


    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loja / Local de Estoque',
                'verbose_name_plural': 'Lojas / Locais de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'ordering': ['produto__nome', 'loja__nome'],
                'indexes': [models.Index(fields=['produto', 'loja'], name='estoque_sal_produto_235d82_idx')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'loja'), name='uniq_produto_loja')],
            },
        ),
    ]
