# Generated by Django 5.2.6 on 2025-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_add_produto_especificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='loja',
            constraint=models.UniqueConstraint(condition=models.Q(('is_central', True)), fields=('is_central',), name='uniq_loja_central_true'),
        ),
    ]
