# Generated by Django 5.2.6 on 2025-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_loja_is_central_loja_uniq_loja_central_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo mínimo (Central)'),
        ),
        migrations.AddIndex(
            model_name='saldoestoque',
            index=models.Index(fields=['loja', 'quantidade'], name='estoque_sal_loja_id_9b381b_idx'),
        ),
    ]
