# Generated by Django 5.2.6 on 2025-10-17 16:20

import django.db.models.deletion
import ordens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ('-data_abertura',), 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='solucao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AndamentoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(blank=True, default='')),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('INTERNO', 'Interno')], default='PUBLICO', max_length=10)),
                ('status_de', models.CharField(blank=True, default='', max_length=15)),
                ('status_para', models.CharField(blank=True, default='', max_length=15)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='AnexoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=ordens.models.os_upload_path)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ordens.ordemservico')),
            ],
            options={
                'ordering': ('-enviado_em',),
            },
        ),
    ]
