# Generated by Django 5.2.6 on 2025-11-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_alter_ordemservico_options_ordemservico_custo_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Problema',
                'verbose_name_plural': 'Categorias de Problema',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='ordens.categoriaproblema'),
        ),
    ]
