# Generated by Django 5.2.6 on 2025-10-16 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0008_remove_produto_quantidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateTimeField()),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('referencia_os', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_destino', to='estoque.loja')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_origem', to='estoque.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_responsavel', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='viagens.veiculo')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='viagens_via_status_41305f_idx'), models.Index(fields=['data_partida'], name='viagens_via_data_pa_c1271b_idx'), models.Index(fields=['origem', 'destino'], name='viagens_via_origem__6b008d_idx')],
            },
        ),
    ]
