# Generated by Django 5.2.6 on 2025-10-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='referencia_os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='ordens.ordemservico'),
        ),
    ]
