# Generated by Django 5.2.6 on 2025-10-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
        ('viagens', '0002_alter_viagem_options_alter_viagem_referencia_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='km_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='km_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='referencia_os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='ordens.ordemservico'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='viagens.veiculo'),
        ),
    ]
