# Generated by Django 5.2.6 on 2025-10-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_viagem_km_final_viagem_km_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='km_final',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='km_inicial',
        ),
    ]
