# Generated by Django 5.2.6 on 2025-10-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_remove_viagem_km_final_remove_viagem_km_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ('-data_partida',), 'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
    ]
