# Generated by Django 5.2.6 on 2025-12-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0009_movimentacao'),
        ('ordens', '0003_categoriaproblema_ordemservico_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome fantasia')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('tipo_servico', models.CharField(max_length=100, verbose_name='Tipo de serviço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=150, verbose_name='Equipamento')),
                ('numero_serie', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número de série')),
                ('descricao_defeito', models.TextField(verbose_name='Descrição do defeito')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta (aguardando envio)'), ('ENVIADA', 'Enviada ao prestador'), ('EM_ANALISE', 'Em análise'), ('AG_ORCAMENTO', 'Aguardando orçamento'), ('APROVADA', 'Aprovada (em execução)'), ('AG_PECA', 'Aguardando peça'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta'), ('C', 'Crítica')], default='M', max_length=1, verbose_name='Prioridade')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de envio')),
                ('data_previsao_retorno', models.DateField(blank=True, null=True, verbose_name='Previsão de retorno')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data de retorno')),
                ('numero_os_prestador', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nº OS prestador')),
                ('valor_orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor orçado')),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aprovado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.loja', verbose_name='Loja / Local de estoque')),
                ('os_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordens.ordemservico', verbose_name='OS interna')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestadores.prestadorservico', verbose_name='Prestador')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
